spring.application.name=ecl

# MySQL
spring.datasource.mysql.url=${MYSQL_DB_URL}
spring.datasource.mysql.username=${MYSQL_DB_USERNAME}
spring.datasource.mysql.password=${MYSQL_DB_PASSWORD}
spring.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver

# Informix
spring.datasource.ifx.url=${IFX_DB_URL}
spring.datasource.ifx.username=${IFX_DB_USERNAME}
spring.datasource.ifx.password=${IFX_DB_PASSWORD}
spring.datasource.ifx.driver-class-name=com.informix.jdbc.IfxDriver

# add hikari for DB connection pool management
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=10000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.pool-name=MyHikariPool

springdoc.api-docs.enabled=true

springdoc.swagger-ui.enabled=true

# Set context root for the management endpoints
server.servlet.context-path=/eclRest

# Enable the health endpoint
management.endpoint.health.access=read_only

# Customize health endpoint path
management.endpoints.web.base-path=/app-health

# Enable only specific health indicators (optional)
management.health.db.enabled=true
management.health.diskspace.enabled=true

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized





